TARGET_W_GR_FAILED = [];
TARGET_DISTANCE_FROM_CENTER_GR_FAILED = [];

TARGET_W_MR_FAILED = [];
TARGET_DISTANCE_FROM_CENTER_MR_FAILED = [];

TARGET_W_GR_SUCCESSFUL = [];
TARGET_DISTANCE_FROM_CENTER_GR_SUCCESSFUL = [];

TARGET_W_MR_SUCCESSFUL = [];
TARGET_DISTANCE_FROM_CENTER_MR_SUCCESSFUL = [];

for i = 1:size(TIMEOUT)
   if TIMEOUT(i) == 1
       
       if strcmp(STATE(i), 'MANUAL_RECORDED')
           TARGET_W_MR_FAILED = [TARGET_W_MR_FAILED; TARGET_W(i)];
           TARGET_DISTANCE_FROM_CENTER_MR_FAILED = [TARGET_DISTANCE_FROM_CENTER_MR_FAILED; DISTANCE_FROM_CENTER(i)];
       end
       
       if strcmp(STATE(i), 'GAZE_RECORDED')
               TARGET_W_GR_FAILED = [TARGET_W_GR_FAILED; TARGET_W(i)];
               TARGET_DISTANCE_FROM_CENTER_GR_FAILED = [TARGET_DISTANCE_FROM_CENTER_GR_FAILED; DISTANCE_FROM_CENTER(i)];
       end
       
   else
       
       if strcmp(STATE(i), 'MANUAL_RECORDED')
           TARGET_W_MR_SUCCESSFUL = [TARGET_W_MR_SUCCESSFUL; TARGET_W(i)];
           TARGET_DISTANCE_FROM_CENTER_MR_SUCCESSFUL = [TARGET_DISTANCE_FROM_CENTER_MR_SUCCESSFUL; DISTANCE_FROM_CENTER(i)];
       end
       
       if strcmp(STATE(i), 'GAZE_RECORDED')
               TARGET_W_GR_SUCCESSFUL = [TARGET_W_GR_SUCCESSFUL; TARGET_W(i)];
               TARGET_DISTANCE_FROM_CENTER_GR_SUCCESSFUL = [TARGET_DISTANCE_FROM_CENTER_GR_SUCCESSFUL; DISTANCE_FROM_CENTER(i)];
       end
       
   end
end

TARGET_W_FAILED = [TARGET_W_MR_FAILED; TARGET_W_GR_FAILED];
TARGET_DISTANCE_FROM_CENTER_FAILED = [TARGET_DISTANCE_FROM_CENTER_MR_FAILED; TARGET_DISTANCE_FROM_CENTER_GR_FAILED];

figure;
plot(TARGET_W_GR_FAILED, TARGET_DISTANCE_FROM_CENTER_GR_FAILED, 'r*', ...
TARGET_W_MR_FAILED, TARGET_DISTANCE_FROM_CENTER_MR_FAILED, 'c*', ...
TARGET_W_GR_SUCCESSFUL, TARGET_DISTANCE_FROM_CENTER_GR_SUCCESSFUL, 'go',...
TARGET_W_MR_SUCCESSFUL, TARGET_DISTANCE_FROM_CENTER_MR_SUCCESSFUL, 'bo');

legend('failed gaze-supported trials', 'failed manual trials', 'successful gaze-supported trials', 'successful manual trials')

xlabel('target size');
ylabel('distance from center');
title('Recorded trials based on target charactaristics');

clear TARGET_W_FAILED;
clear TARGET_DISTANCE_FROM_CENTER_FAILED;
clear i;