% NOTE: this depends on the values generated by running the script: TRAINING_count_timeouts_per_participant_all_levels

disp('FZ: U-Test of Total Fails Per Participant for All Training Levels (Manual vs. Gaze)')
myBoxPlotter(GT_TOTAL_FAILS' ,MT_TOTAL_FAILS' ,'total_fails_MW_fig')
legend('manual-based', 'gaze-supported')
xlabel('modality')
ylabel('Total trial fails')
title('FZ: Total Fails for All Training Levels');