% NOTE: this depends on the values generated by running the script: TRAINING_count_timeouts_per_participant_all_levels

disp('FZ: U-Test of Total Successes Per Participant for All Training Levels (Manual vs. Gaze)')
myBoxPlotter(MT_TOTAL_SUCCESSES' ,GT_TOTAL_SUCCESSES' ,'total_successes_MW_fig')
legend('manual-based', 'gaze-supported')
xlabel('modality')
ylabel('Total trial successes')
title('FZ: Total Successes for All Training Levels');